#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class Caja
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private string mDescripcion;
		public virtual string Descripcion
		{
			get
			{
				return this.mDescripcion;
			}
			set
			{
				this.mDescripcion = value;
			}
		}
		
		private DateTime? mCierre;
		public virtual DateTime? Cierre
		{
			get
			{
				return this.mCierre;
			}
			set
			{
				this.mCierre = value;
			}
		}
		
		private double? mSaldo;
		public virtual double? Saldo
		{
			get
			{
				return this.mSaldo;
			}
			set
			{
				this.mSaldo = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
	}
}
#pragma warning restore 1591
