#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class CarpetaCatastralAnual
	{
		private double? mValor;
		public virtual double? Valor
		{
			get
			{
				return this.mValor;
			}
			set
			{
				this.mValor = value;
			}
		}
		
		private string mNombres;
		public virtual string Nombres
		{
			get
			{
				return this.mNombres;
			}
			set
			{
				this.mNombres = value;
			}
		}
		
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private string mDenominacion;
		public virtual string Denominacion
		{
			get
			{
				return this.mDenominacion;
			}
			set
			{
				this.mDenominacion = value;
			}
		}
		
		private int? mConcepto;
		public virtual int? Concepto
		{
			get
			{
				return this.mConcepto;
			}
			set
			{
				this.mConcepto = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private double? mBaseimponible;
		public virtual double? BaseImponible
		{
			get
			{
				return this.mBaseimponible;
			}
			set
			{
				this.mBaseimponible = value;
			}
		}
		
		private int? mAño;
		public virtual int? Año
		{
			get
			{
				return this.mAño;
			}
			set
			{
				this.mAño = value;
			}
		}
		
	}
}
#pragma warning restore 1591
