#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class Cobro
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mContribuyente;
		public virtual int? Contribuyente
		{
			get
			{
				return this.mContribuyente;
			}
			set
			{
				this.mContribuyente = value;
			}
		}
		
		private DateTime? mFecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.mFecha;
			}
			set
			{
				this.mFecha = value;
			}
		}
		
		private int? mFormapago;
		public virtual int? FormaPago
		{
			get
			{
				return this.mFormapago;
			}
			set
			{
				this.mFormapago = value;
			}
		}
		
		private string mFormapagoatributos;
		public virtual string FormaPagoAtributos
		{
			get
			{
				return this.mFormapagoatributos;
			}
			set
			{
				this.mFormapagoatributos = value;
			}
		}
		
		private int? mUsuario;
		public virtual int? Usuario
		{
			get
			{
				return this.mUsuario;
			}
			set
			{
				this.mUsuario = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private double? mValor;
		public virtual double? Valor
		{
			get
			{
				return this.mValor;
			}
			set
			{
				this.mValor = value;
			}
		}
		
		private Contribuyente mContribuyente1;
		public virtual Contribuyente ContribuyenteNav
		{
			get
			{
				return this.mContribuyente1;
			}
			set
			{
				this.mContribuyente1 = value;
			}
		}
		
		private IList<CobroTransaccion> mCobrostransacciones = new List<CobroTransaccion>();
		public virtual IList<CobroTransaccion> TransaccionesNav
		{
			get
			{
				return this.mCobrostransacciones;
			}
		}
		
		private IList<CobrosElemento> mCobroselementos = new List<CobrosElemento>();
		public virtual IList<CobrosElemento> ElementosNav
		{
			get
			{
				return this.mCobroselementos;
			}
		}
		
		private IList<CobrosRubro> mCobrosrubros = new List<CobrosRubro>();
		public virtual IList<CobrosRubro> RubrosNav
		{
			get
			{
				return this.mCobrosrubros;
			}
		}
		
	}
}
#pragma warning restore 1591
