#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class CobrosNotasElemento
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mNota;
		public virtual int? Nota
		{
			get
			{
				return this.mNota;
			}
			set
			{
				this.mNota = value;
			}
		}
		
		private int? mTransaccion;
		public virtual int? Transaccion
		{
			get
			{
				return this.mTransaccion;
			}
			set
			{
				this.mTransaccion = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private CobrosNota mCobrosnota;
		public virtual CobrosNota Cobrosnota
		{
			get
			{
				return this.mCobrosnota;
			}
			set
			{
				this.mCobrosnota = value;
			}
		}
		
	}
}
#pragma warning restore 1591
