#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class CobroTransaccion
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mCobro;
		public virtual int? Cobro
		{
			get
			{
				return this.mCobro;
			}
			set
			{
				this.mCobro = value;
			}
		}
		
		private int? mTransaccion;
		public virtual int? Transaccion
		{
			get
			{
				return this.mTransaccion;
			}
			set
			{
				this.mTransaccion = value;
			}
		}
		
		private double? mValor;
		public virtual double? Valor
		{
			get
			{
				return this.mValor;
			}
			set
			{
				this.mValor = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private double? mRecargos;
		public virtual double? Recargos
		{
			get
			{
				return this.mRecargos;
			}
			set
			{
				this.mRecargos = value;
			}
		}
		
		private double? mRebajas;
		public virtual double? Rebajas
		{
			get
			{
				return this.mRebajas;
			}
			set
			{
				this.mRebajas = value;
			}
		}
		
		private int? mSoportenumero;
		public virtual int? SoporteNumero
		{
			get
			{
				return this.mSoportenumero;
			}
			set
			{
				this.mSoportenumero = value;
			}
		}
		
	}
}
#pragma warning restore 1591
