#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class CobrosElemento
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mCobro;
		public virtual int? Cobro
		{
			get
			{
				return this.mCobro;
			}
			set
			{
				this.mCobro = value;
			}
		}
		
		private int? mFormapago;
		public virtual int? FormaPago
		{
			get
			{
				return this.mFormapago;
			}
			set
			{
				this.mFormapago = value;
			}
		}
		
		private DateTime? mFecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.mFecha;
			}
			set
			{
				this.mFecha = value;
			}
		}
		
		private int? mNumero;
		public virtual int? Numero
		{
			get
			{
				return this.mNumero;
			}
			set
			{
				this.mNumero = value;
			}
		}
		
		private int? mEntidad;
		public virtual int? Entidad
		{
			get
			{
				return this.mEntidad;
			}
			set
			{
				this.mEntidad = value;
			}
		}
		
		private string mNombres;
		public virtual string Nombres
		{
			get
			{
				return this.mNombres;
			}
			set
			{
				this.mNombres = value;
			}
		}
		
		private string mDenominacion;
		public virtual string Denominacion
		{
			get
			{
				return this.mDenominacion;
			}
			set
			{
				this.mDenominacion = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private int? mTipo;
		public virtual int? Tipo
		{
			get
			{
				return this.mTipo;
			}
			set
			{
				this.mTipo = value;
			}
		}
		
		private int? mAutorizacion;
		public virtual int? Autorizacion
		{
			get
			{
				return this.mAutorizacion;
			}
			set
			{
				this.mAutorizacion = value;
			}
		}
		
		private string mComentario;
		public virtual string Comentario
		{
			get
			{
				return this.mComentario;
			}
			set
			{
				this.mComentario = value;
			}
		}
		
		private double? mValor;
		public virtual double? Valor
		{
			get
			{
				return this.mValor;
			}
			set
			{
				this.mValor = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
	}
}
#pragma warning restore 1591
