#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class CoeficienteElemento
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mCoeficiente;
		public virtual int? Coeficiente
		{
			get
			{
				return this.mCoeficiente;
			}
			set
			{
				this.mCoeficiente = value;
			}
		}
		
		private int? mClave;
		public virtual int? Clave
		{
			get
			{
				return this.mClave;
			}
			set
			{
				this.mClave = value;
			}
		}
		
		private string mDenominacion;
		public virtual string Denominacion
		{
			get
			{
				return this.mDenominacion;
			}
			set
			{
				this.mDenominacion = value;
			}
		}
		
		private double? mValor;
		public virtual double? Valor
		{
			get
			{
				return this.mValor;
			}
			set
			{
				this.mValor = value;
			}
		}
		
		private double? mValor1;
		public virtual double? Valor1
		{
			get
			{
				return this.mValor1;
			}
			set
			{
				this.mValor1 = value;
			}
		}
		
		private double? mValor2;
		public virtual double? Valor2
		{
			get
			{
				return this.mValor2;
			}
			set
			{
				this.mValor2 = value;
			}
		}
		
		private double? mValor3;
		public virtual double? Valor3
		{
			get
			{
				return this.mValor3;
			}
			set
			{
				this.mValor3 = value;
			}
		}
		
		private double? mValor4;
		public virtual double? Valor4
		{
			get
			{
				return this.mValor4;
			}
			set
			{
				this.mValor4 = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private int? mEnterodesde;
		public virtual int? EnteroDesde
		{
			get
			{
				return this.mEnterodesde;
			}
			set
			{
				this.mEnterodesde = value;
			}
		}
		
		private int? mEnterohasta;
		public virtual int? EnteroHasta
		{
			get
			{
				return this.mEnterohasta;
			}
			set
			{
				this.mEnterohasta = value;
			}
		}
		
		private double? mMontodesde;
		public virtual double? MontoDesde
		{
			get
			{
				return this.mMontodesde;
			}
			set
			{
				this.mMontodesde = value;
			}
		}
		
		private double? mMontohasta;
		public virtual double? MontoHasta
		{
			get
			{
				return this.mMontohasta;
			}
			set
			{
				this.mMontohasta = value;
			}
		}
		
		private Coeficiente mCoeficiente1;
		public virtual Coeficiente CoeficienteNav
		{
			get
			{
				return this.mCoeficiente1;
			}
			set
			{
				this.mCoeficiente1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
