#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class ContribuyentesRebaja
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mContribuyente;
		public virtual int? Contribuyente
		{
			get
			{
				return this.mContribuyente;
			}
			set
			{
				this.mContribuyente = value;
			}
		}
		
		private int? mAño;
		public virtual int? Año
		{
			get
			{
				return this.mAño;
			}
			set
			{
				this.mAño = value;
			}
		}
		
		private int? mRebaja;
		public virtual int? Rebaja
		{
			get
			{
				return this.mRebaja;
			}
			set
			{
				this.mRebaja = value;
			}
		}
		
		private int? mPersonal;
		public virtual int? Personal
		{
			get
			{
				return this.mPersonal;
			}
			set
			{
				this.mPersonal = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private double? mFraccion;
		public virtual double? Fraccion
		{
			get
			{
				return this.mFraccion;
			}
			set
			{
				this.mFraccion = value;
			}
		}
		
		private Rebaja mRebaja1;
		public virtual Rebaja RebajaNav
		{
			get
			{
				return this.mRebaja1;
			}
			set
			{
				this.mRebaja1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
