#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class CuentaCorrienteItem
	{
		private int? _id;
		public virtual int? id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int? _concepto;
		public virtual int? concepto
		{
			get
			{
				return this._concepto;
			}
			set
			{
				this._concepto = value;
			}
		}
		
		private string _nombres;
		public virtual string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				this._nombres = value;
			}
		}
		
		private string _codigo;
		public virtual string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				this._codigo = value;
			}
		}
		
		private string _direccion;
		public virtual string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				this._direccion = value;
			}
		}
		
		private int? _año;
		public virtual int? año
		{
			get
			{
				return this._año;
			}
			set
			{
				this._año = value;
			}
		}
		
		private double? _total;
		public virtual double? total
		{
			get
			{
				return this._total;
			}
			set
			{
				this._total = value;
			}
		}
		
	}
}
#pragma warning restore 1591
