#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class CuentaBancaria
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private string mNumerocuenta;
		public virtual string NumeroCuenta
		{
			get
			{
				return this.mNumerocuenta;
			}
			set
			{
				this.mNumerocuenta = value;
			}
		}
		
		private int? mBanco;
		public virtual int? Banco
		{
			get
			{
				return this.mBanco;
			}
			set
			{
				this.mBanco = value;
			}
		}
		
		private int? mTipo;
		public virtual int? Tipo
		{
			get
			{
				return this.mTipo;
			}
			set
			{
				this.mTipo = value;
			}
		}
		
		private string mAgente;
		public virtual string Agente
		{
			get
			{
				return this.mAgente;
			}
			set
			{
				this.mAgente = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private TablaClave mTablaclave;
		public virtual TablaClave Tablaclave
		{
			get
			{
				return this.mTablaclave;
			}
			set
			{
				this.mTablaclave = value;
			}
		}
		
	}
}
#pragma warning restore 1591
