#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class MejoraElemento
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mMejora;
		public virtual int? Mejora
		{
			get
			{
				return this.mMejora;
			}
			set
			{
				this.mMejora = value;
			}
		}
		
		private int? mPredio;
		public virtual int? Predio
		{
			get
			{
				return this.mPredio;
			}
			set
			{
				this.mPredio = value;
			}
		}
		
		private int? mContribuyente;
		public virtual int? Contribuyente
		{
			get
			{
				return this.mContribuyente;
			}
			set
			{
				this.mContribuyente = value;
			}
		}
		
		private double? mLongitud;
		public virtual double? Longitud
		{
			get
			{
				return this.mLongitud;
			}
			set
			{
				this.mLongitud = value;
			}
		}
		
		private double? mValorpropiedad;
		public virtual double? ValorPropiedad
		{
			get
			{
				return this.mValorpropiedad;
			}
			set
			{
				this.mValorpropiedad = value;
			}
		}
		
		private double? mAlicuota;
		public virtual double? Alicuota
		{
			get
			{
				return this.mAlicuota;
			}
			set
			{
				this.mAlicuota = value;
			}
		}
		
		private double? mTotal;
		public virtual double? Total
		{
			get
			{
				return this.mTotal;
			}
			set
			{
				this.mTotal = value;
			}
		}
		
		private double? mDividendo;
		public virtual double? Dividendo
		{
			get
			{
				return this.mDividendo;
			}
			set
			{
				this.mDividendo = value;
			}
		}
		
		private int? mEmisiones;
		public virtual int? Emisiones
		{
			get
			{
				return this.mEmisiones;
			}
			set
			{
				this.mEmisiones = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private PredioBase mPrediobase;
		public virtual PredioBase PredioNav
		{
			get
			{
				return this.mPrediobase;
			}
			set
			{
				this.mPrediobase = value;
			}
		}
		
		private Contribuyente mContribuyente1;
		public virtual Contribuyente ContribuyenteNav
		{
			get
			{
				return this.mContribuyente1;
			}
			set
			{
				this.mContribuyente1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
