#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class Mejora
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private string mDenominacion;
		public virtual string Denominacion
		{
			get
			{
				return this.mDenominacion;
			}
			set
			{
				this.mDenominacion = value;
			}
		}
		
		private string mDecripcion;
		public virtual string Decripcion
		{
			get
			{
				return this.mDecripcion;
			}
			set
			{
				this.mDecripcion = value;
			}
		}
		
		private double? mMontoinvertido;
		public virtual double? MontoInvertido
		{
			get
			{
				return this.mMontoinvertido;
			}
			set
			{
				this.mMontoinvertido = value;
			}
		}
		
		private double? mRecuperacionmonto;
		public virtual double? RecuperacionMonto
		{
			get
			{
				return this.mRecuperacionmonto;
			}
			set
			{
				this.mRecuperacionmonto = value;
			}
		}
		
		private int? mRecuperacionaños;
		public virtual int? RecuperacionAños
		{
			get
			{
				return this.mRecuperacionaños;
			}
			set
			{
				this.mRecuperacionaños = value;
			}
		}
		
		private double? mRecuperacionporcentaje;
		public virtual double? RecuperacionPorcentaje
		{
			get
			{
				return this.mRecuperacionporcentaje;
			}
			set
			{
				this.mRecuperacionporcentaje = value;
			}
		}
		
		private int? mRecuperacionemisiones;
		public virtual int? RecuperacionEmisiones
		{
			get
			{
				return this.mRecuperacionemisiones;
			}
			set
			{
				this.mRecuperacionemisiones = value;
			}
		}
		
		private int? mPrediosconteo;
		public virtual int? PrediosConteo
		{
			get
			{
				return this.mPrediosconteo;
			}
			set
			{
				this.mPrediosconteo = value;
			}
		}
		
		private double? mSumaavaluos;
		public virtual double? SumaAvaluos
		{
			get
			{
				return this.mSumaavaluos;
			}
			set
			{
				this.mSumaavaluos = value;
			}
		}
		
		private int? mDividendotipo;
		public virtual int? DividendoTipo
		{
			get
			{
				return this.mDividendotipo;
			}
			set
			{
				this.mDividendotipo = value;
			}
		}
		
		private double? mDividendovalor;
		public virtual double? DividendoValor
		{
			get
			{
				return this.mDividendovalor;
			}
			set
			{
				this.mDividendovalor = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private IList<MejoraElemento> mMejoraselementos = new List<MejoraElemento>();
		public virtual IList<MejoraElemento> ElementosNav
		{
			get
			{
				return this.mMejoraselementos;
			}
		}
		
	}
}
#pragma warning restore 1591
