#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class PlanillaAtributo
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private string mDenominacion;
		public virtual string Denominacion
		{
			get
			{
				return this.mDenominacion;
			}
			set
			{
				this.mDenominacion = value;
			}
		}
		
		private int? mPlanilla;
		public virtual int? Planilla
		{
			get
			{
				return this.mPlanilla;
			}
			set
			{
				this.mPlanilla = value;
			}
		}
		
		private int? mAtributo;
		public virtual int? Atributo
		{
			get
			{
				return this.mAtributo;
			}
			set
			{
				this.mAtributo = value;
			}
		}
		
		private int? mTipo;
		public virtual int? Tipo
		{
			get
			{
				return this.mTipo;
			}
			set
			{
				this.mTipo = value;
			}
		}
		
		private int? mValori;
		public virtual int? ValorI
		{
			get
			{
				return this.mValori;
			}
			set
			{
				this.mValori = value;
			}
		}
		
		private double? mValord;
		public virtual double? ValorD
		{
			get
			{
				return this.mValord;
			}
			set
			{
				this.mValord = value;
			}
		}
		
		private string mValorc;
		public virtual string ValorC
		{
			get
			{
				return this.mValorc;
			}
			set
			{
				this.mValorc = value;
			}
		}
		
		private DateTime? mValorf;
		public virtual DateTime? ValorF
		{
			get
			{
				return this.mValorf;
			}
			set
			{
				this.mValorf = value;
			}
		}
		
		private string mValorb;
		public virtual string ValorB
		{
			get
			{
				return this.mValorb;
			}
			set
			{
				this.mValorb = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
	}
}
#pragma warning restore 1591
