#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class PlanillaSustitucion
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private DateTime? mFecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.mFecha;
			}
			set
			{
				this.mFecha = value;
			}
		}
		
		private int? mOriginal;
		public virtual int? Original
		{
			get
			{
				return this.mOriginal;
			}
			set
			{
				this.mOriginal = value;
			}
		}
		
		private int? mNueva;
		public virtual int? Nueva
		{
			get
			{
				return this.mNueva;
			}
			set
			{
				this.mNueva = value;
			}
		}
		
		private string mComentarios;
		public virtual string Comentarios
		{
			get
			{
				return this.mComentarios;
			}
			set
			{
				this.mComentarios = value;
			}
		}
		
		private int? mUsuario;
		public virtual int? Usuario
		{
			get
			{
				return this.mUsuario;
			}
			set
			{
				this.mUsuario = value;
			}
		}
		
		private Planilla mPlanilla;
		public virtual Planilla PlanillaNav
		{
			get
			{
				return this.mPlanilla;
			}
			set
			{
				this.mPlanilla = value;
			}
		}
		
		private Planilla mPlanilla1;
		public virtual Planilla PlanillaNavi
		{
			get
			{
				return this.mPlanilla1;
			}
			set
			{
				this.mPlanilla1 = value;
			}
		}
		
		private Usuario mUsuario1;
		public virtual Usuario UsuarioNav
		{
			get
			{
				return this.mUsuario1;
			}
			set
			{
				this.mUsuario1 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
