#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class Planilla
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private int? mConcepto;
		public virtual int? Concepto
		{
			get
			{
				return this.mConcepto;
			}
			set
			{
				this.mConcepto = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private int? mAño;
		public virtual int? Año
		{
			get
			{
				return this.mAño;
			}
			set
			{
				this.mAño = value;
			}
		}
		
		private int? mMes;
		public virtual int? Mes
		{
			get
			{
				return this.mMes;
			}
			set
			{
				this.mMes = value;
			}
		}
		
		private int? mContribuyente;
		public virtual int? Contribuyente
		{
			get
			{
				return this.mContribuyente;
			}
			set
			{
				this.mContribuyente = value;
			}
		}
		
		private int? mServicio;
		public virtual int? Servicio
		{
			get
			{
				return this.mServicio;
			}
			set
			{
				this.mServicio = value;
			}
		}
		
		private double? mTotal;
		public virtual double? Total
		{
			get
			{
				return this.mTotal;
			}
			set
			{
				this.mTotal = value;
			}
		}
		
		private double? mPagos;
		public virtual double? Pagos
		{
			get
			{
				return this.mPagos;
			}
			set
			{
				this.mPagos = value;
			}
		}
		
		private double? mRecargos;
		public virtual double? Recargos
		{
			get
			{
				return this.mRecargos;
			}
			set
			{
				this.mRecargos = value;
			}
		}
		
		private double? mRebajas;
		public virtual double? Rebajas
		{
			get
			{
				return this.mRebajas;
			}
			set
			{
				this.mRebajas = value;
			}
		}
		
		private double? mConvenios;
		public virtual double? Convenios
		{
			get
			{
				return this.mConvenios;
			}
			set
			{
				this.mConvenios = value;
			}
		}
		
		private DateTime? mFechaemision;
		public virtual DateTime? FechaEmision
		{
			get
			{
				return this.mFechaemision;
			}
			set
			{
				this.mFechaemision = value;
			}
		}
		
		private DateTime? mFechacancelacion;
		public virtual DateTime? FechaCancelacion
		{
			get
			{
				return this.mFechacancelacion;
			}
			set
			{
				this.mFechacancelacion = value;
			}
		}
		
		private int? mUsuario;
		public virtual int? Usuario
		{
			get
			{
				return this.mUsuario;
			}
			set
			{
				this.mUsuario = value;
			}
		}
		
		private string mComentarios;
		public virtual string Comentarios
		{
			get
			{
				return this.mComentarios;
			}
			set
			{
				this.mComentarios = value;
			}
		}
		
		private int? mNumero;
		public virtual int? Numero
		{
			get
			{
				return this.mNumero;
			}
			set
			{
				this.mNumero = value;
			}
		}
		
		private int? mEspecie;
		public virtual int? Especie
		{
			get
			{
				return this.mEspecie;
			}
			set
			{
				this.mEspecie = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private string mContribuyentes;
		public virtual string Contribuyentes
		{
			get
			{
				return this.mContribuyentes;
			}
			set
			{
				this.mContribuyentes = value;
			}
		}
		
		private int? mSoportenumero;
		public virtual int? SoporteNumero
		{
			get
			{
				return this.mSoportenumero;
			}
			set
			{
				this.mSoportenumero = value;
			}
		}
		
		private Contribuyente mContribuyente1;
		public virtual Contribuyente ContribuyenteNav
		{
			get
			{
				return this.mContribuyente1;
			}
			set
			{
				this.mContribuyente1 = value;
			}
		}
		
		private Concepto mConcepto1;
		public virtual Concepto ConceptoNav
		{
			get
			{
				return this.mConcepto1;
			}
			set
			{
				this.mConcepto1 = value;
			}
		}
		
		private IList<PlanillaRubro> mPlanillasrubros = new List<PlanillaRubro>();
		public virtual IList<PlanillaRubro> RubrosNav
		{
			get
			{
				return this.mPlanillasrubros;
			}
		}
		
		private IList<PlanillaAtributo> mPlanillasatributos = new List<PlanillaAtributo>();
		public virtual IList<PlanillaAtributo> AtributosNav
		{
			get
			{
				return this.mPlanillasatributos;
			}
		}
		
		private IList<PlanillaMes> mPlanillasmeses = new List<PlanillaMes>();
		public virtual IList<PlanillaMes> PlanillaMesesNav
		{
			get
			{
				return this.mPlanillasmeses;
			}
		}
		
	}
}
#pragma warning restore 1591
