#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class RepCtaCteAnualItem
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private int? _rUBRO_ID;
		public virtual int? RUBRO_ID
		{
			get
			{
				return this._rUBRO_ID;
			}
			set
			{
				this._rUBRO_ID = value;
			}
		}
		
		private double? _vALOR;
		public virtual double? VALOR
		{
			get
			{
				return this._vALOR;
			}
			set
			{
				this._vALOR = value;
			}
		}
		
		private string _rUBRO;
		public virtual string RUBRO
		{
			get
			{
				return this._rUBRO;
			}
			set
			{
				this._rUBRO = value;
			}
		}
		
		private string _nOMBRES;
		public virtual string NOMBRES
		{
			get
			{
				return this._nOMBRES;
			}
			set
			{
				this._nOMBRES = value;
			}
		}
		
		private string _cODIGO;
		public virtual string CODIGO
		{
			get
			{
				return this._cODIGO;
			}
			set
			{
				this._cODIGO = value;
			}
		}
		
	}
}
#pragma warning restore 1591
