#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class RepPredio
	{
		private int? mZonahomogenea;
		public virtual int? ZonaHomogenea
		{
			get
			{
				return this.mZonahomogenea;
			}
			set
			{
				this.mZonahomogenea = value;
			}
		}
		
		private double? mValorpropiedad;
		public virtual double? ValorPropiedad
		{
			get
			{
				return this.mValorpropiedad;
			}
			set
			{
				this.mValorpropiedad = value;
			}
		}
		
		private int? mTipopropiedad;
		public virtual int? TipoPropiedad
		{
			get
			{
				return this.mTipopropiedad;
			}
			set
			{
				this.mTipopropiedad = value;
			}
		}
		
		private double? mSuperficie;
		public virtual double? Superficie
		{
			get
			{
				return this.mSuperficie;
			}
			set
			{
				this.mSuperficie = value;
			}
		}
		
		private string mNombres;
		public virtual string Nombres
		{
			get
			{
				return this.mNombres;
			}
			set
			{
				this.mNombres = value;
			}
		}
		
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private bool? mEscritura;
		public virtual bool? Escritura
		{
			get
			{
				return this.mEscritura;
			}
			set
			{
				this.mEscritura = value;
			}
		}
		
		private int? mDominio;
		public virtual int? Dominio
		{
			get
			{
				return this.mDominio;
			}
			set
			{
				this.mDominio = value;
			}
		}
		
		private string mDireccion;
		public virtual string Direccion
		{
			get
			{
				return this.mDireccion;
			}
			set
			{
				this.mDireccion = value;
			}
		}
		
		private bool? mConstruido;
		public virtual bool? Construido
		{
			get
			{
				return this.mConstruido;
			}
			set
			{
				this.mConstruido = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private int? mClasetierra;
		public virtual int? ClaseTierra
		{
			get
			{
				return this.mClasetierra;
			}
			set
			{
				this.mClasetierra = value;
			}
		}
		
		private double? mAvaluoterreno;
		public virtual double? AvaluoTerreno
		{
			get
			{
				return this.mAvaluoterreno;
			}
			set
			{
				this.mAvaluoterreno = value;
			}
		}
		
		private double? mAvaluoconstruccion;
		public virtual double? AvaluoConstruccion
		{
			get
			{
				return this.mAvaluoconstruccion;
			}
			set
			{
				this.mAvaluoconstruccion = value;
			}
		}
		
		private int? mZona;
		public virtual int? Zona
		{
			get
			{
				return this.mZona;
			}
			set
			{
				this.mZona = value;
			}
		}
		
		private int? mSector;
		public virtual int? Sector
		{
			get
			{
				return this.mSector;
			}
			set
			{
				this.mSector = value;
			}
		}
		
		private int? mPredio;
		public virtual int? Predio
		{
			get
			{
				return this.mPredio;
			}
			set
			{
				this.mPredio = value;
			}
		}
		
		private int? mPoligono;
		public virtual int? Poligono
		{
			get
			{
				return this.mPoligono;
			}
			set
			{
				this.mPoligono = value;
			}
		}
		
		private int? mManzana;
		public virtual int? Manzana
		{
			get
			{
				return this.mManzana;
			}
			set
			{
				this.mManzana = value;
			}
		}
		
		private int? mFormatocodigo;
		public virtual int? FormatoCodigo
		{
			get
			{
				return this.mFormatocodigo;
			}
			set
			{
				this.mFormatocodigo = value;
			}
		}
		
		private string mDivision;
		public virtual string Division
		{
			get
			{
				return this.mDivision;
			}
			set
			{
				this.mDivision = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private string mCedula;
		public virtual string Cedula
		{
			get
			{
				return this.mCedula;
			}
			set
			{
				this.mCedula = value;
			}
		}
		
		private double? mAreaconstruccion;
		public virtual double? AreaConstruccion
		{
			get
			{
				return this.mAreaconstruccion;
			}
			set
			{
				this.mAreaconstruccion = value;
			}
		}
		
	}
}
#pragma warning restore 1591
