#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class RepRecaudacionesCompDetalle
	{
		private double? mValor;
		public virtual double? Valor
		{
			get
			{
				return this.mValor;
			}
			set
			{
				this.mValor = value;
			}
		}
		
		private int? mRubroid;
		public virtual int? Rubroid
		{
			get
			{
				return this.mRubroid;
			}
			set
			{
				this.mRubroid = value;
			}
		}
		
		private string mRubro;
		public virtual string Rubro
		{
			get
			{
				return this.mRubro;
			}
			set
			{
				this.mRubro = value;
			}
		}
		
		private string mNombres;
		public virtual string Nombres
		{
			get
			{
				return this.mNombres;
			}
			set
			{
				this.mNombres = value;
			}
		}
		
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private DateTime? mFecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.mFecha;
			}
			set
			{
				this.mFecha = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private int? mConceptoid;
		public virtual int? Conceptoid
		{
			get
			{
				return this.mConceptoid;
			}
			set
			{
				this.mConceptoid = value;
			}
		}
		
		private string mConcepto;
		public virtual string Concepto
		{
			get
			{
				return this.mConcepto;
			}
			set
			{
				this.mConcepto = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private int? mAnio;
		public virtual int? Anio
		{
			get
			{
				return this.mAnio;
			}
			set
			{
				this.mAnio = value;
			}
		}
		
		private int? mOrigen;
		public virtual int? Origen
		{
			get
			{
				return this.mOrigen;
			}
			set
			{
				this.mOrigen = value;
			}
		}
		
	}
}
#pragma warning restore 1591
