#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace Intelligob.Entidades	
{
	public partial class ResumenEmisionesPeriodoItem
	{
		private string _concepto;
		public virtual string concepto
		{
			get
			{
				return this._concepto;
			}
			set
			{
				this._concepto = value;
			}
		}
		
		private string _rubro;
		public virtual string rubro
		{
			get
			{
				return this._rubro;
			}
			set
			{
				this._rubro = value;
			}
		}
		
		private double? _valor;
		public virtual double? valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				this._valor = value;
			}
		}
		
		private int? _propiedad;
		public virtual int? propiedad
		{
			get
			{
				return this._propiedad;
			}
			set
			{
				this._propiedad = value;
			}
		}
		
	}
}
#pragma warning restore 1591
