#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Intelligob.Entidades;

namespace Intelligob.Entidades	
{
	public partial class Servicio
	{
		private int mId;
		public virtual int Id
		{
			get
			{
				return this.mId;
			}
			set
			{
				this.mId = value;
			}
		}
		
		private string mCodigo;
		public virtual string Codigo
		{
			get
			{
				return this.mCodigo;
			}
			set
			{
				this.mCodigo = value;
			}
		}
		
		private string mDenominacion;
		public virtual string Denominacion
		{
			get
			{
				return this.mDenominacion;
			}
			set
			{
				this.mDenominacion = value;
			}
		}
		
		private int? mContribuyente;
		public virtual int? Contribuyente
		{
			get
			{
				return this.mContribuyente;
			}
			set
			{
				this.mContribuyente = value;
			}
		}
		
		private string mDireccion;
		public virtual string Direccion
		{
			get
			{
				return this.mDireccion;
			}
			set
			{
				this.mDireccion = value;
			}
		}
		
		private string mSector;
		public virtual string Sector
		{
			get
			{
				return this.mSector;
			}
			set
			{
				this.mSector = value;
			}
		}
		
		private int? mCategoria;
		public virtual int? Categoria
		{
			get
			{
				return this.mCategoria;
			}
			set
			{
				this.mCategoria = value;
			}
		}
		
		private int? mEstado;
		public virtual int? Estado
		{
			get
			{
				return this.mEstado;
			}
			set
			{
				this.mEstado = value;
			}
		}
		
		private int? mTipo;
		public virtual int? Tipo
		{
			get
			{
				return this.mTipo;
			}
			set
			{
				this.mTipo = value;
			}
		}
		
		private double? mLectura;
		public virtual double? Lectura
		{
			get
			{
				return this.mLectura;
			}
			set
			{
				this.mLectura = value;
			}
		}
		
		private DateTime? mFecha;
		public virtual DateTime? Fecha
		{
			get
			{
				return this.mFecha;
			}
			set
			{
				this.mFecha = value;
			}
		}
		
		private Contribuyente mContribuyenteNav;
		public virtual Contribuyente ContribuyenteNav
		{
			get
			{
				return this.mContribuyenteNav;
			}
			set
			{
				this.mContribuyenteNav = value;
			}
		}
		
	}
}
#pragma warning restore 1591
