#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Code is generated by Telerik Data Access Service Wizard
// using RestItemInfoList.tt template

namespace IntelligobMovil
{
	using System.ServiceModel;
	using System.ServiceModel.Web;
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;

	/// <summary>
	/// Item info list class handler. Used for transporting a list of item infos.
	/// </summary>
	/// <typeparam name="TItem">The type of the item info's wrapped object.</typeparam>
	[DataContract(Name = "ItemInfoList", Namespace = "")]
	public class ItemInfoList<TItem> where TItem : class
	{
	    /// <summary>
	    /// Initializes a new instance of the <see cref="ItemInfoLis<TItem>"/> class.
	    /// </summary>
	    /// <param name="items">The item info list.</param>
	    /// <param name="nextPageLink">The next page link.</param>
	    /// <param name="previousPageLink">The previous page link.</param>
	    public ItemInfoList(
	        List<ItemInfo<TItem>> items, 
	        Uri nextPageLink, 
	        Uri previousPageLink)
	    {
	        this.NextPage = nextPageLink;
	        this.PreviousPage = previousPageLink;
	        this.InfoList = items;
	    }
	
	    /// <summary>
	    /// Gets or sets the item info list.
	    /// </summary>
	    /// <value>The item info list.</value>
	    [DataMember]
	    public List<ItemInfo<TItem>> InfoList { get; private set; }
	
	    /// <summary>
	    /// Gets or sets the next page link.
	    /// </summary>
	    /// <value>The next page link.</value>
	    [DataMember]
	    public Uri NextPage { get; private set; }
	
	    /// <summary>
	    /// Gets or sets the previous page link.
	    /// </summary>
	    /// <value>The previous page link.</value>
	    [DataMember]
	    public Uri PreviousPage { get; private set; }
	}
}
#pragma warning restore 1591
